name: Create diagram

on:
  push:
    paths:
      - 'diagram.svg'

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github"    
